import React from 'react';
import type { ReactElement } from 'react';
import Head from 'next/head';
import BaseButton from '../components/BaseButton';
import CardBox from '../components/CardBox';
import SectionFullScreen from '../components/SectionFullScreen';
import LayoutGuest from '../layouts/Guest';
import { Field, Form, Formik } from 'formik';
import FormField from '../components/FormField';
import FormCheckRadio from '../components/FormCheckRadio';
import BaseDivider from '../components/BaseDivider';
import BaseButtons from '../components/BaseButtons';
import { getPageTitle } from '../config';
import Link from 'next/link';
import CardBoxComponentTitle from '../components/CardBoxComponentTitle';
import BaseIcon from '../components/BaseIcon';
import { mdiInformation } from '@mdi/js';

export default function Starter() {
  return (
    <>
      <Head>
        <title>{getPageTitle('Starter Page')}</title>
      </Head>

      <SectionFullScreen bg='violet'>
        <CardBox className='w-11/12 md:w-7/12 lg:w-6/12 xl:w-4/12'>
          <CardBoxComponentTitle title='Welcome to your MyTestProject app!' />
          <BaseDivider />
          <div className='space-y-3'>
            <p className='text-center'>
              This is Vue/nodejs app generated by the{' '}
              <a
                className='text-blue-600'
                href='https://flatlogic.com/generator'
              >
                Flatlogic Web App Generator
              </a>
            </p>
            <p className='text-center'>
              For guides and documentation please check your local README.md and{' '}
              <a
                className='text-blue-600'
                href='https://flatlogic.com/documentation'
              >
                Flatlogic documentation
              </a>
            </p>
          </div>
          <BaseDivider />
          <BaseButtons>
            <BaseButton
              href='/login'
              label='Login'
              color='info'
              className='w-full'
            />
          </BaseButtons>
          <div className='grid grid-cols-1 gap-2 lg:grid-cols-4 mt-2'>
            <div className='text-center'>
              <a className='text-blue-600' href='https://react.dev/'>
                React JS
              </a>
            </div>

            <div className='text-center'>
              <a className='text-blue-600' href='https://tailwindcss.com/'>
                Tailwind CSS
              </a>
            </div>
            <div className='text-center'>
              <a className='text-blue-600' href='https://nodejs.org/en'>
                Node JS CSS
              </a>
            </div>
            <div className='text-center'>
              <a className='text-blue-600' href='https://flatlogic.com/forum'>
                Flatlogic Forum
              </a>
            </div>
          </div>
        </CardBox>
      </SectionFullScreen>
    </>
  );
}

Starter.getLayout = function getLayout(page: ReactElement) {
  return <LayoutGuest>{page}</LayoutGuest>;
};
